apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  containers:
    - name: container1
      image: nginx
      ports:
        - containerPort: 80
    - name: container2
      image: redis
      ports:
        - containerPort: 6379
